---
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: Build cli-mod
        run: |
          pnpm --filter cli-mod install
          pnpm --filter cli-mod run build
      - name: Install dependencies
        run: pnpm install
      - name: Build all workspaces
        run: pnpm -r build
      - name: Get Version from package.json and Commit Message
        id: get-version-commit
        run: |
          ver=$(node -e "console.log(require('./src/core/package.json').version)")
          msg=$(git log -1 --pretty=format:'%B')
          echo "VER=$ver" >> $GITHUB_ENV
          echo "Version: $ver" > ./resources/update-log.txt
          echo "Commit Message: $msg" >> ./resources/update-log.txt
      - name: Build userscript
        run: pnpm build
      - name: Publish to OSS
        uses: wxh06/dist2oss@v1
        with:
          version: ${{ env.VER }}
          stable: ${{ !contains( env.VER, '-' ) }}
          access-key-id: ${{ secrets.OSS_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET }}
          bucket: exlg-celeste
          region: oss-cn-shanghai
          pattern: dist/extend-luogu.min.user.js


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Build cli-mod
        run: |
          pnpm --filter cli-mod install
          pnpm --filter cli-mod run build
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm
        run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
